server:
  port: 5000
  servlet:
    context-path: /api/v1

  spring:
    datasource:
      url: jdbc:h2:mem:testdb
      driverClassName: org.h2.Driver
      username: sa
      password:
      database-platform: org.hibernate.dialect.H2Dialect
spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update